gaps inner 5
gaps outer 0
smart_gaps on
default_border pixel 0
default_floating_border normal 0

seat * xcursor_theme Adwaita 24

set $bg #141210
set $bg_alt #221E1A
set $fg #F5EFE7
set $fg_alt #847568
set $muted #6B5E53
set $accent #352D27
set $urgent #FF5F6D
set $warning #D8A85F

# class                 border      background  text        indicator   child_border
client.focused          $bg_alt     $bg_alt     #ffffff     $bg_alt     $bg_alt
client.focused_inactive $bg_alt     $bg_alt     $fg_alt     $bg_alt     $bg_alt
client.unfocused        $bg_alt     $bg_alt     $muted      $bg_alt     $bg_alt
client.urgent           $urgent     $urgent     $bg         $urgent     $urgent
client.placeholder      $bg         $bg         $muted      $bg         $bg
