# toxic — ported from alacritty toxic.toml

background            #0f111a
foreground            #d6deeb
selection_background  #ffd580
selection_foreground  #0f111a

cursor                #d6deeb
cursor_text_color     #0f111a

mark1_background      #ffd580
mark1_foreground      #0f111a

# normal
color0  #0f111a
color1  #ff5874
color2  #8aff80
color3  #ffd580
color4  #68b0ff
color5  #c792ea
color6  #4cd5c3
color7  #d6deeb

# bright
color8   #181b22
color9   #ff7c99
color10  #a7ff57
color11  #ffe58f
color12  #82aaff
color13  #b480d6
color14  #89ddff
color15  #e6edf3

# indexed 16/17 from alacritty
color16  #ffcb6b
color17  #a7ff57
