exec dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP

exec dex --autostart --environment sway

# notifications
exec mako

# screen sharing portal (wlroots backend)
exec /usr/libexec/xdg-desktop-portal-wlr -r

# shadowsocks
exec ss-local -c ~/.ss-helsinki.json -u

# xray
# exec xray -config /usr/local/etc/xray/config.json

# wallpaper
exec swaybg -i ~/images/2560x1440.jpg -m fill

exec kitty -e tmux
exec firefox
