input * {
    xkb_layout "us,ru"
    xkb_options "grp:alt_shift_toggle"
}

bindsym XF86AudioRaiseVolume exec ~/.local/bin/volume-osd up
bindsym XF86AudioLowerVolume exec ~/.local/bin/volume-osd down
bindsym XF86AudioMute exec ~/.local/bin/volume-osd mute
bindsym XF86AudioMicMute exec ~/.local/bin/volume-osd micmute

bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous

bindsym Shift+Control+s exec grim -g "$(slurp)" - | wl-copy --type image/png

floating_modifier none
tiling_drag enable
