# assign [app_id="Alacritty"] 1
# assign [class="Alacritty"] 1
# for_window [app_id="Alacritty"] border pixel 0
# for_window [class="Alacritty"] border pixel 0

assign [app_id="kitty"] 1
for_window [app_id="kitty"] border pixel 0

# assign [app_id="firefox"] 2
# assign [class="Firefox"] 2
for_window [app_id="firefox"] border pixel 0
for_window [class="Firefox"] border pixel 0

assign [app_id="steam"] 3
assign [class="steam"] 3

for_window [class="^steam_app_0$" title="^Battle\.net$"] move to workspace 3
for_window [class="steam_app_0" title="World of Warcraft"] border pixel 0, move to workspace 4

for_window [app_id="pavucontrol"] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [app_id="zmk-studio"] floating enable
for_window [class="Zmk-studio"] floating enable
