bar {
    position top
    font pango:JetBrainsMono Nerd Font 16
    status_command i3blocks
    separator_symbol " ⎪ "
    colors {
        background $bg
        statusline $fg
        separator  $fg_alt

        focused_workspace  $accent $accent #ffffff
        active_workspace   $bg_alt $bg_alt $fg_alt
        inactive_workspace $bg $bg $muted
        urgent_workspace   $urgent $urgent $bg
        binding_mode       $warning $warning $bg
    }
}
