assign [class="Alacritty"] 1
# assign [class="Firefox"] 2
assign [class="steam"] 3

for_window [class="^steam_app_0$" title="^Battle\.net$"] move to workspace 3
for_window [class="steam_app_0" title="World of Warcraft"] border pixel 0, move to workspace 4

for_window [class="pavucontrol"] floating enable
for_window [class="Zmk-studio"] floating enable
