-- vim.api.nvim_create_autocmd("VimLeave", {
-- 	group = vim.api.nvim_create_augroup("reset_cursor_on_exit", { clear = true }),
-- 	callback = function()
-- 		vim.opt.guicursor = "a:ver25"
-- 	end,
-- })
